use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'CDNByeSDK_Example' do
  pod 'CDNByeSDK', :path => '../'

  target 'CDNByeSDK_Tests' do
    inherit! :search_paths

    
  end
end
